### ISSUE TITLE
coredump on ubuntu 21.04 with libbpf 0.6.1 and libbpf 0.7.0

### ISSUE THREAD

**Issue by cfc4n** [kris-nova/boopkit#9]
hi whitehat, coredump on ubuntu 21.04, and what env you used ?
## env
os:ubuntu 21.04
kernel: Linux vm-server 5.11.0-49-generic #55-Ubuntu SMP Wed Jan 12 17:36:34 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
golang:go version go1.17.2 linux/amd64
clang:Ubuntu clang version 12.0.0-3ubuntu1~21.04.2
libbpf:0.6.1/0.7.0
## how to reproduce
![coredump](https://user-images.githubusercontent.com/709947/163012383-ee7df7bf-51b8-4a96-b8f1-fc21fa46236b.jpg)

```shell
make
sudo make install
boopkit -x 127.0.0.1
  -> Logs: cat /sys/kernel/tracing/trace_pipe
  -> Loading eBPF Probe: /root/.boopkit/pr0be.safe.o
  -> Obfuscating PID: 12973
  -> eBPF Probe loaded: /root/.boopkit/pr0be.safe.o
  -> Loading eBPF Probe: /root/.boopkit/pr0be.boop.o
libbpf: failed to find BTF for extern 'inet_ntop' [28] section: -2
Segmentation fault
```

## debug with gdb
![gdb](https://user-images.githubusercontent.com/709947/163012366-05a50a29-1cb9-47b4-a1e3-d482e6b58d40.jpg)
![und-section](https://user-images.githubusercontent.com/709947/163012389-cb2fdc47-9885-4858-8e7e-cca2e8be3b6e.jpg)

## why

why linker create two `*UND*` section into `pr0be.boop.o` for `inet_ntop` and `inet_pton`.
how can it works?

thanks.

**Comment by kris-nova** [comment]
CC @fkautz

**Comment by kris-nova** [comment]
Its an implicit reference to the glibc `<arpa/inet.h>` I believe. I can try to recreate and follow up with an answer.

**Comment by kris-nova** [comment]
I pushed a commit that uses the autogenerated `vmlinux.h` instead of including libbpf and glibc directly.

https://github.com/kris-nova/boopkit/commit/328d4bf429a53eb9cf2c090003580b3360c5e377

You should be able to compile if you run from HEAD.

Please share if this does not work.

**Comment by cfc4n** [comment]
the bug is not fixed... still error with "libbpf: failed to find BTF for extern 'inet_ntop' [28] section: -2"

can you give your environment？
